apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applicationsets
spec:
  project: default
  source:
    repoURL: "https://github.com/yurgas/edu-argocd-from-helm.git"
    path: appsets
    targetRevision: main
  destination:
    namespace: argocd
    name: in-cluster
  syncPolicy:
    automated: {}
