apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# resources:
# - crds.yaml

helmCharts:
- name: prometheus
  repo: https://prometheus-community.github.io/helm-charts
  version: 48.1.1
  releaseName: prometheus-operator
  namespace: prometheus-operator
  valuesFile: values.yaml
  includeCRDs: true
