apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: grafana
  project: default
  source:
    helm:
      releaseName: grafana
      values: |
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
            - name: Prometheus
              type: prometheus
              url: http://prometheus-kube-prometheus-prometheus.prometheus-operator
              access: proxy
              isDefault: true          
        dashboardProviders:
          dashboardproviders.yaml:
            apiVersion: 1
            providers:
            - name: 'default'
              orgId: 1
              folder: ''
              type: file
              disableDeletion: false
              editable: true
              options:
                path: /var/lib/grafana/dashboards/default     
        dashboards:
          default:
            argo-cd:
              url: https://raw.githubusercontent.com/argoproj/argo-cd/master/examples/dashboard.json
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.58.4
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
