apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: prometheus
  project: default
  source:
    helm:
      releaseName: prometheus
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 48.1.1
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
