apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator
spec:
  project: default
  source:
    repoURL: "https://github.com/yurgas/edu-argocd-from-helm.git"
    path: apps/prometheus-operator
    targetRevision: main
  destination:
    namespace: prometheus-operator
    name: in-cluster
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
