apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: prometheus
  project: default
  source:
    helm:
      releaseName: prometheus
    chart: prometheus
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 23.1.0
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
